// swift-tools-version: 6.2

// SPDX-FileCopyrightText: 2026 GooBeom Jeoung
// SPDX-License-Identifier: GPL-3.0-only

import PackageDescription

let package = Package(
    name: "Roamling",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v13)
    ],
    products: [
        .executable(name: "Roamling", targets: ["RoamlingApp"]),
        .executable(name: "RoamlingLogicTests", targets: ["RoamlingLogicTests"]),
        .library(name: "RoamlingCore", targets: ["RoamlingCore"]),
        .library(name: "RoamlingPet", targets: ["RoamlingPet"]),
        .library(name: "RoamlingSources", targets: ["RoamlingSources"]),
        .library(name: "RoamlingEngine", targets: ["RoamlingEngine"]),
        .library(name: "RoamlingShell", targets: ["RoamlingShell"])
    ],
    targets: [
        .target(name: "RoamlingCore"),
        // The C surface uniffi generates. A systemLibrary target so the module
        // reaches whatever imports RoamlingCoreRs, not just RoamlingCoreRs.
        .systemLibrary(name: "CRoamlingCoreFFI", path: "Sources/CRoamlingCoreFFI"),
        // The Rust core's Swift bindings, generated by scripts/build-rust-core.sh
        // and linked statically against .build/rust/libroamling_core.a. The
        // unsafe flags are why this package is an app rather than a dependency;
        // SwiftPM has no first-class way to link a sibling toolchain's output.
        .target(
            name: "RoamlingCoreRs",
            dependencies: ["CRoamlingCoreFFI"],
            path: "Sources/RoamlingCoreRs",
            exclude: ["README.md"],
            sources: ["roamling_core.swift"],
            linkerSettings: [
                .unsafeFlags(["-L.build/rust", "-lroamling_core"])
            ]
        ),
        // Foundation only since W2: decoding is the platform's job and every
        // other step is arithmetic on bytes.
        .target(
            name: "RoamlingPet",
            dependencies: ["RoamlingCore"],
            resources: [
                .process("Resources")
            ]
        ),
        // The app's orchestration. Since the agent integrations are injected it
        // no longer knows RoamlingSources exists, which is what lets the tick
        // loop move somewhere the hook transport has not gone yet.
        .target(
            name: "RoamlingEngine",
            dependencies: ["RoamlingCore", "RoamlingPet", "RoamlingCoreRs"]
        ),
        // The user-facing surface with no widgets in it: the menu tree, the
        // words, and what the alerts say. Each platform renders this rather
        // than restating it.
        .target(
            name: "RoamlingShell",
            dependencies: ["RoamlingCore", "RoamlingPet", "RoamlingEngine"],
            resources: [
                .process("Resources")
            ]
        ),
        .target(
            name: "RoamlingMac",
            dependencies: [
                "RoamlingCore", "RoamlingPet", "RoamlingSources", "RoamlingEngine", "RoamlingShell"
            ],
            linkerSettings: [
                .linkedFramework("AppKit"),
                .linkedFramework("CoreGraphics"),
                .linkedFramework("ScreenCaptureKit"),
                .linkedFramework("SwiftUI")
            ]
        ),
        // Foundation and BSD sockets since W3: the loopback receiver stopped
        // needing Apple's Network framework, which was one of the two lines
        // that would not compile on Windows.
        .target(
            name: "RoamlingSources",
            dependencies: ["RoamlingCore"]
        ),
        .executableTarget(
            name: "RoamlingApp",
            dependencies: ["RoamlingMac"]
        ),
        .executableTarget(
            name: "RoamlingLogicTests",
            dependencies: [
                "RoamlingCore", "RoamlingPet", "RoamlingSources", "RoamlingEngine",
                "RoamlingShell", "RoamlingCoreRs"
            ],
            path: "Tests/RoamlingLogicTests",
            // The recorded session is read by path, not from a bundle, so that
            // regenerating it is a plain file write.
            exclude: ["RuntimeTrace.txt"],
            linkerSettings: [
                .linkedFramework("ImageIO"),
                .linkedFramework("UniformTypeIdentifiers")
            ]
        )
    ]
)
